name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-code:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_15.4.app
    - name: Build Package
      run: swift build
    - name: Run Tests
      run: swift test
